name: Publish package to NPM
on:
  push:
    tags:
      - "v**"

jobs:
  publish:
    if: github.event.base_ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"
          scope: "@soundify"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          run_install: true
          version: latest

      - name: build and publish
        run: pnpm build && pnpm publish --ignore-scripts --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
