name: Publish package to NPM
on:
  push:
    tags:
      - "v**"

jobs:
  publish:
    if: github.event.base_ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Test
        run: deno test -A
        env:
          SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          run_install: false
          version: 7.29.1

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Build
        run: deno task build

      - name: Get tag version
        if: startsWith(github.ref, 'refs/tags/')
        id: get_tag_version
        run: echo ::set-output name=TAG_VERSION::${GITHUB_REF/refs\/tags\//}

      - name: npm build
        run: deno run -A ./scripts/build.ts ${{steps.get_tag_version.outputs.TAG_VERSION}}

      - name: npm publish
        if: startsWith(github.ref, 'refs/tags/')
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          pnpm config set //registry.npmjs.org/:_authToken '${NPM_TOKEN}'
          cd dist
          cd ./shared/ && pnpm publish --ignore-scripts --access public --no-git-checks && cd ..
          cd ./api/ && pnpm publish --ignore-scripts --access public --no-git-checks && cd ..
          cd ./web/ && pnpm publish --ignore-scripts --access public --no-git-checks && cd ..
          cd ./node/ && pnpm publish --ignore-scripts --access public --no-git-checks
